// ── Config & Errors ───────────────────────────────────────────────────────────
export { ShaderConfig }    from './core/ShaderConfig.js'
export { ShaderNodeError } from './core/ShaderNodeError.js'
export type { ErrorLevel } from './core/ShaderConfig.js'

// ── Core abstracts ────────────────────────────────────────────────────────────
export { ShaderNode }   from './core/ShaderNode.js'
export { InputNode }    from './core/InputNode.js'
export { OutputNode }   from './core/OutputNode.js'
export { ProcessNode }  from './core/ProcessNode.js'

// ── Sockets ───────────────────────────────────────────────────────────────────
export { InputSocket }      from './core/InputSocket.js'
export { OutputSocket }     from './core/OutputSocket.js'
export { SOCKET_GLSL_TYPE } from './core/SocketType.js'
export type { SocketType }  from './core/SocketType.js'

// ── Compiler ──────────────────────────────────────────────────────────────────
export { CompileContext }        from './core/CompileContext.js'
export type { CompiledMaterial } from './core/CompileContext.js'

// ── Input nodes ───────────────────────────────────────────────────────────────
export { TextureCoordinate } from './nodes/input/TextureCoordinate.js'
export { Value }             from './nodes/input/Value.js'
export { RGB }               from './nodes/input/RGB.js'
export { Geometry }          from './nodes/input/Geometry.js'
export { LayerWeight }       from './nodes/input/LayerWeight.js'
export { CameraData }        from './nodes/input/CameraData.js'
export { UVMap }             from './nodes/input/UVMap.js'
export { Tangent }           from './nodes/input/Tangent.js'
export { ColorAttribute }    from './nodes/input/ColorAttribute.js'
export { Attribute }         from './nodes/input/Attribute.js'
export { Wireframe }         from './nodes/input/Wireframe.js'
export { ObjectInfo }        from './nodes/input/ObjectInfo.js'
export { OceanAttribute }    from './nodes/input/OceanAttribute.js'
export { HairInfo }          from './nodes/input/HairInfo.js'
export { ParticleInfo }      from './nodes/input/ParticleInfo.js'
export { LightPath }         from './nodes/input/LightPath.js'

// ── Output nodes ──────────────────────────────────────────────────────────────
export { MaterialOutput }        from './nodes/output/MaterialOutput.js'
export { Displacement }          from './nodes/output/Displacement.js'
export type { MaterialOutputInputs } from './nodes/output/MaterialOutput.js'
export type { DisplacementInputs }   from './nodes/output/Displacement.js'

// ── Process nodes — Texture ───────────────────────────────────────────────────
export { NoiseTexture }         from './nodes/process/NoiseTexture.js'
export { AnimatedNoiseTexture } from './nodes/process/AnimatedNoiseTexture.js'
export { VoronoiTexture }       from './nodes/process/VoronoiTexture.js'
export { WaveTexture }          from './nodes/process/WaveTexture.js'
export { GradientTexture }      from './nodes/process/GradientTexture.js'
export { BrickTexture }         from './nodes/process/BrickTexture.js'
export { CheckerTexture }       from './nodes/process/CheckerTexture.js'
export { MagicTexture }         from './nodes/process/MagicTexture.js'
export { MusgraveTexture }      from './nodes/process/MusgraveTexture.js'
export { WhiteNoise }           from './nodes/process/WhiteNoise.js'
export { ImageTexture }         from './nodes/process/ImageTexture.js'
export { EnvironmentTexture }  from './nodes/process/EnvironmentTexture.js'

// ── Process nodes — Color ─────────────────────────────────────────────────────
export { ColorRamp }           from './nodes/process/ColorRamp.js'
export { MixRGB }              from './nodes/process/MixRGB.js'
export { HueSaturationValue }  from './nodes/process/HueSaturationValue.js'
export { BrightContrast }      from './nodes/process/BrightContrast.js'
export { RGBtoBW }             from './nodes/process/RGBtoBW.js'
export { Blackbody }           from './nodes/process/Blackbody.js'
export { Gamma }               from './nodes/process/Gamma.js'
export { InvertColor }         from './nodes/process/InvertColor.js'
export { RGBCurves }           from './nodes/process/RGBCurves.js'
export { Wavelength }          from './nodes/process/Wavelength.js'

// ── Process nodes — Vector ────────────────────────────────────────────────────
export { NormalMap }        from './nodes/process/NormalMap.js'
export { Bump }             from './nodes/process/Bump.js'
export { Mapping }          from './nodes/process/Mapping.js'
export { VectorMath }       from './nodes/process/VectorMath.js'
export { SeparateRGB }      from './nodes/process/SeparateRGB.js'
export { CombineRGB }       from './nodes/process/CombineRGB.js'
export { SeparateXYZ }      from './nodes/process/SeparateXYZ.js'
export { CombineXYZ }       from './nodes/process/CombineXYZ.js'
export { Normal }           from './nodes/process/Normal.js'
export { VectorRotate }     from './nodes/process/VectorRotate.js'
export { VectorTransform }  from './nodes/process/VectorTransform.js'
export { VectorCurves }     from './nodes/process/VectorCurves.js'

// ── Process nodes — Shader ────────────────────────────────────────────────────
export { PrincipledBSDF }        from './nodes/process/PrincipledBSDF.js'
export { Emission }              from './nodes/process/Emission.js'
export { VolumeAbsorption }     from './nodes/process/VolumeAbsorption.js'
export { VolumeScatter }        from './nodes/process/VolumeScatter.js'
export { PrincipledVolume }     from './nodes/process/PrincipledVolume.js'
export { MixShader }             from './nodes/process/MixShader.js'
export { AddShader }             from './nodes/process/AddShader.js'
export { Fresnel }               from './nodes/process/Fresnel.js'
export { DiffuseBSDF }           from './nodes/process/DiffuseBSDF.js'
export { GlossyBSDF }            from './nodes/process/GlossyBSDF.js'
export { RefractionBSDF }        from './nodes/process/RefractionBSDF.js'
export { GlassBSDF }             from './nodes/process/GlassBSDF.js'
export { SheenBSDF }             from './nodes/process/SheenBSDF.js'
export { SubsurfaceScattering }  from './nodes/process/SubsurfaceScattering.js'
export { ToonBSDF }              from './nodes/process/ToonBSDF.js'
export { SpecularBSDF }          from './nodes/process/SpecularBSDF.js'
export { TranslucentBSDF }       from './nodes/process/TranslucentBSDF.js'
export { PrincipledHair }        from './nodes/process/PrincipledHair.js'

// ── Process nodes — Converter ─────────────────────────────────────────────────
export { Math as ShaderMath } from './nodes/process/Math.js'
export { Clamp }              from './nodes/process/Clamp.js'
export { MapRange }           from './nodes/process/MapRange.js'
export { FloatCurve }         from './nodes/process/FloatCurve.js'
export { ShaderToRGB }        from './nodes/process/ShaderToRGB.js'
export { CombineColor }       from './nodes/process/CombineColor.js'
export { SeparateColor }      from './nodes/process/SeparateColor.js'
export { HashValue }          from './nodes/process/HashValue.js'

// ── Script node — custom GLSL as a first-class graph node (OSL equivalent) ───
export { ShaderScript }      from './nodes/process/ShaderScript.js'
export type { ShaderScriptConfig, ScriptInputDecl, ScriptOutputDecl } from './nodes/process/ShaderScript.js'

// ── Screen-space / ray-marching nodes ────────────────────────────────────────
export { ScreenCamera }         from './nodes/input/ScreenCamera.js'
export { SchwarzschildMarch }   from './nodes/process/SchwarzschildMarch.js'
export type { SchwarzschildMarchInputs } from './nodes/process/SchwarzschildMarch.js'
export { ScreenOutput }         from './nodes/output/ScreenOutput.js'

// ── Shader nodes ──────────────────────────────────────────────────────────────
export { AmbientOcclusion }  from './nodes/shader/AmbientOcclusion.js'
export type { AmbientOcclusionInputs } from './nodes/shader/AmbientOcclusion.js'
export { RayPortal }         from './nodes/shader/RayPortal.js'
export type { RayPortalInputs } from './nodes/shader/RayPortal.js'

// ── Types ─────────────────────────────────────────────────────────────────────
export type { NoiseTextureInputs }          from './nodes/process/NoiseTexture.js'
export type { AnimatedNoiseTextureInputs }  from './nodes/process/AnimatedNoiseTexture.js'
export type { VoronoiTextureInputs, VoronoiFeature } from './nodes/process/VoronoiTexture.js'
export type { WaveTextureInputs, WaveType, WaveProfile } from './nodes/process/WaveTexture.js'
export type { GradientTextureInputs, GradientType } from './nodes/process/GradientTexture.js'
export type { BrickTextureInputs }          from './nodes/process/BrickTexture.js'
export type { CheckerTextureInputs }        from './nodes/process/CheckerTexture.js'
export type { MagicTextureInputs }          from './nodes/process/MagicTexture.js'
export type { MusgraveTextureInputs, MusgraveType } from './nodes/process/MusgraveTexture.js'
export type { WhiteNoiseInputs }            from './nodes/process/WhiteNoise.js'
export type { ImageTextureInputs }          from './nodes/process/ImageTexture.js'
export type { EnvironmentTextureInputs }   from './nodes/process/EnvironmentTexture.js'
export type { ColorRampInputs }             from './nodes/process/ColorRamp.js'
export type { MixRGBInputs, MixRGBMode }    from './nodes/process/MixRGB.js'
export type { HueSaturationValueInputs }    from './nodes/process/HueSaturationValue.js'
export type { BrightContrastInputs }        from './nodes/process/BrightContrast.js'
export type { RGBtoBWInputs }               from './nodes/process/RGBtoBW.js'
export type { BlackbodyInputs }             from './nodes/process/Blackbody.js'
export type { GammaInputs }                 from './nodes/process/Gamma.js'
export type { InvertColorInputs }           from './nodes/process/InvertColor.js'
export type { RGBCurvesInputs }             from './nodes/process/RGBCurves.js'
export type { WavelengthInputs }            from './nodes/process/Wavelength.js'
export type { NormalMapInputs }             from './nodes/process/NormalMap.js'
export type { BumpInputs }                  from './nodes/process/Bump.js'
export type { MappingInputs, MappingMode }  from './nodes/process/Mapping.js'
export type { VectorMathInputs, VectorMathMode } from './nodes/process/VectorMath.js'
export type { SeparateRGBInputs }           from './nodes/process/SeparateRGB.js'
export type { CombineRGBInputs }            from './nodes/process/CombineRGB.js'
export type { SeparateXYZInputs }           from './nodes/process/SeparateXYZ.js'
export type { CombineXYZInputs }            from './nodes/process/CombineXYZ.js'
export type { NormalInputs }                from './nodes/process/Normal.js'
export type { VectorRotateInputs, VectorRotateMode } from './nodes/process/VectorRotate.js'
export type { VectorTransformInputs, VectorTransformSpace, VectorTransformType } from './nodes/process/VectorTransform.js'
export type { VectorCurvesInputs }          from './nodes/process/VectorCurves.js'
export type { PrincipledBSDFInputs }        from './nodes/process/PrincipledBSDF.js'
export type { EmissionInputs }              from './nodes/process/Emission.js'
export type { VolumeAbsorptionInputs }      from './nodes/process/VolumeAbsorption.js'
export type { VolumeScatterInputs }         from './nodes/process/VolumeScatter.js'
export type { PrincipledVolumeInputs }      from './nodes/process/PrincipledVolume.js'
export type { MixShaderInputs }             from './nodes/process/MixShader.js'
export type { AddShaderInputs }             from './nodes/process/AddShader.js'
export type { FresnelInputs }               from './nodes/process/Fresnel.js'
export type { DiffuseBSDFInputs }           from './nodes/process/DiffuseBSDF.js'
export type { GlossyBSDFInputs }            from './nodes/process/GlossyBSDF.js'
export type { RefractionBSDFInputs }        from './nodes/process/RefractionBSDF.js'
export type { GlassBSDFInputs }             from './nodes/process/GlassBSDF.js'
export type { SheenBSDFInputs }             from './nodes/process/SheenBSDF.js'
export type { SubsurfaceScatteringInputs }  from './nodes/process/SubsurfaceScattering.js'
export type { ToonBSDFInputs }              from './nodes/process/ToonBSDF.js'
export type { SpecularBSDFInputs }          from './nodes/process/SpecularBSDF.js'
export type { TranslucentBSDFInputs }       from './nodes/process/TranslucentBSDF.js'
export type { PrincipledHairInputs }        from './nodes/process/PrincipledHair.js'
export type { MathInputs, MathMode }        from './nodes/process/Math.js'
export type { ClampInputs, ClampMode }      from './nodes/process/Clamp.js'
export type { MapRangeInputs, MapRangeMode } from './nodes/process/MapRange.js'
export type { FloatCurveInputs }            from './nodes/process/FloatCurve.js'
export type { ShaderToRGBInputs }           from './nodes/process/ShaderToRGB.js'
export type { CombineColorInputs, CombineColorMode } from './nodes/process/CombineColor.js'
export type { SeparateColorInputs, SeparateColorMode } from './nodes/process/SeparateColor.js'
export type { HashValueInputs }             from './nodes/process/HashValue.js'
