// ── Core ──────────────────────────────────────────────────────────────────────
export { BasePass }         from './core/BasePass.js'
export { CompositorOutput } from './core/CompositorOutput.js'
export type { CompositorBackend }       from './core/CompositorBackend.js'
export type { PassRegistry }            from './core/BasePass.js'
export type { CompositorOutputOptions } from './core/CompositorOutput.js'

// ── Pass nodes ────────────────────────────────────────────────────────────────
export { Bloom }               from './passes/Bloom.js'
export { DepthOfField }        from './passes/DepthOfField.js'
export { Blur }                from './passes/Blur.js'
export { ChromaticAberration } from './passes/ChromaticAberration.js'
export { Vignette }            from './passes/Vignette.js'
export { FilmGrain }           from './passes/FilmGrain.js'
export { ColorBalance }        from './passes/ColorBalance.js'
export { HueSaturation }       from './passes/HueSaturation.js'
export { BrightnessContrast }  from './passes/BrightnessContrast.js'
export { Gamma }               from './passes/Gamma.js'
export { Exposure }            from './passes/Exposure.js'
export { Mix }                 from './passes/Mix.js'
export { Pixelate }            from './passes/Pixelate.js'
export { Sharpen }             from './passes/Sharpen.js'
export { AlphaOver }           from './passes/AlphaOver.js'
export { SetAlpha }            from './passes/SetAlpha.js'
export { ZCombine }            from './passes/ZCombine.js'
export { SeparateRGBA }        from './passes/SeparateRGBA.js'
export { CombineRGBA }         from './passes/CombineRGBA.js'
export { SSAO }                from './passes/SSAO.js'
export { SSR }                 from './passes/SSR.js'

// ── Option types ──────────────────────────────────────────────────────────────
export type { BloomOptions }               from './passes/Bloom.js'
export type { DepthOfFieldOptions }        from './passes/DepthOfField.js'
export type { BlurOptions }                from './passes/Blur.js'
export type { ChromaticAberrationOptions } from './passes/ChromaticAberration.js'
export type { VignetteOptions }            from './passes/Vignette.js'
export type { FilmGrainOptions }           from './passes/FilmGrain.js'
export type { ColorBalanceOptions }        from './passes/ColorBalance.js'
export type { HueSaturationOptions }       from './passes/HueSaturation.js'
export type { BrightnessContrastOptions }  from './passes/BrightnessContrast.js'
export type { GammaOptions }               from './passes/Gamma.js'
export type { ExposureOptions }            from './passes/Exposure.js'
export type { MixOptions }                 from './passes/Mix.js'
export type { PixelateOptions }            from './passes/Pixelate.js'
export type { SharpenOptions }             from './passes/Sharpen.js'
export type { AlphaOverOptions }           from './passes/AlphaOver.js'
export type { SetAlphaOptions }            from './passes/SetAlpha.js'
export type { ZCombineOptions }            from './passes/ZCombine.js'
export type { SeparateRGBAOptions, RGBAChannel } from './passes/SeparateRGBA.js'
export type { CombineRGBAOptions }         from './passes/CombineRGBA.js'
export type { SSAOOptions }                from './passes/SSAO.js'
export type { SSROptions }                 from './passes/SSR.js'
export { RenderLayers }   from './passes/RenderLayers.js'
export { GaussianBlur }   from './passes/GaussianBlur.js'
export { GlareStreaks }   from './passes/GlareStreaks.js'
export { MotionBlur }     from './passes/MotionBlur.js'
export type { RenderLayersOptions } from './passes/RenderLayers.js'
export type { GaussianBlurOptions } from './passes/GaussianBlur.js'
export type { GlareStreaksOptions } from './passes/GlareStreaks.js'
export type { MotionBlurOptions }   from './passes/MotionBlur.js'
export { LensFlare }    from './passes/LensFlare.js'
export { EdgeDetect }   from './passes/EdgeDetect.js'
export type { LensFlareOptions }  from './passes/LensFlare.js'
export type { EdgeDetectOptions } from './passes/EdgeDetect.js'
export { LUT }              from './passes/LUT.js'
export type { LUTOptions }  from './passes/LUT.js'
